### ISSUE TITLE
`cryptography.fernet.InvalidToken` intermitent error

### ISSUE THREAD

**Issue by tam203** [informatics-lab/aml-jupyterhub#35]
I've been getting the error below intermittently. I've not quite got to the bottom but I suspect it happens when I 'login with AD' through the hub, then restart the server. Then when spawning the instance I get this error. logging out and in again fixes it.
```
    Traceback (most recent call last):
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/jupyterhub/handlers/pages.py", line 245, in post
        await self.spawn_single_user(user, server_name=server_name, options=options)
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 938, in spawn_single_user
        await gen.with_timeout(
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/jupyterhub/user.py", line 656, in spawn
        raise e
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/jupyterhub/user.py", line 560, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/azureuser/aml-jupyterhub/aml_jupyterhub/aml_spawner.py", line 329, in start
        auth_state = await decrypt(self.user.encrypted_auth_state)
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/jupyterhub/crypto.py", line 156, in _decrypt
        decrypted = self.fernet.decrypt(encrypted)
      File "/home/azureuser/miniconda3/envs/aml/lib/python3.8/site-packages/cryptography/fernet.py", line 182, in decrypt
        raise InvalidToken
    cryptography.fernet.InvalidToken
```

**Comment by pierocor** [comment]
I am not completely sure but this is most probably caused by a concurrent JupyterHub app using the same Service Principal's name creating a conflict in the authenticator's encryption token  (i.e. `JUPYTERHUB_CRYPT_KEY`, automatically set in `setenv.sh`). A workaround has been implemented in [this commit](https://github.com/informatics-lab/aml-jupyterhub/commit/62dc5f8653bde2bdef9934e42a4d69561f865622). Setting the `SERVICE_PRINCIPAL_NAME` in the `.env` file with a unique name should solve the problem.

**Comment by pierocor** [comment]
My previous answer is wrong. This happens because of encrypted user's data stored in a browser cookie by a previous JupyterHub instance. These data, returned by OAuth at login and encrypted with the key defined in the `JUPYTERHUB_CRYPT_KEY` variable, are used when the spawner starts. If the variable changes (e.g.  sourcing again `setenv.sh`) the InvalidToken error appears. When the user manually logs out and in, the authentication data in the cookie are overwritten.

**Comment by tam203** [comment]
Good research @pierocor - I think this is solved when running on kubernettes by storing some of this information somewhere persistent. I don't think this is worth worrying about at this stage unless there is a very easy suggestion.

Suggest closing. - Re-open by all means if intending to resolve/progress.
